[package]
name = "uo-ucsp-thesis"
version = "0.2.0"
entrypoint = "src/lib.typ"
description = "Template no oficial para tesis de grado en la Universidad Cat√≥lica San Pablo"
categories = [ "thesis" ]
disciplines = [ "engineering" ]
compiler = "0.13.0"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = ""
