[package]
name = "uo-ucsp-thesis"
version = "0.3.0"
entrypoint = "src/lib.typ"
description = "Unofficial thesis template for the faculty of Civil Engineering at UCSP"
categories = ["thesis"]
disciplines = ["engineering"]
compiler = "0.13.0"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = ""
